service:
  AppMode:  debug
  HttpPort:  :8080

redis:
  host: 127.0.0.1
  port: 6379
  name: 0
  password: ""
  poolSize: 100

mysql:
  db: mysql
  dbHost: 127.0.0.1
  dbPort: 3306
  dbUser: root
  dbPassword: root
  dbName: todo_list1

